book_shop/urls.py
from django.urls import path
from book_shop.views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('catalog/', CatalogView.as_view(), name='catalog'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('book/<int:id>/', DetailBookView.as_view(), name='book-detail'),
    path('create/', CreateBookView.as_view(), name='create-book'),
    path('create/author', CreateAuthorView.as_view(), name='create-author'),
    path('create/genre', CreateGenreView.as_view(), name='create-genre'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_shop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_shop/models/author.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=50, verbose_name='Автор книги')

    def __str__(self):
        return self.name

book_shop/models/book.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name='Название')
    author = models.ForeignKey('Author', on_delete=models.CASCADE, verbose_name='Автор')
    description = models.TextField(max_length=300, null=False, blank=False, verbose_name='Описание')
    image = models.ImageField(upload_to='photos', null=False, blank=False, verbose_name='Изображения')
    article = models.CharField(max_length=6, unique=True, verbose_name='Артикл')
    genres = models.ManyToManyField('Genre', verbose_name='Жанры')
    publication_date = models.DateField(verbose_name='Дата публикации')
    price = models.PositiveIntegerField(default=0, verbose_name='Цена')
    is_available = models.BooleanField(default=True, verbose_name='В наличии')
    language = models.ManyToManyField('Language', verbose_name='Языки')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    def __str__(self):
        return self.title

book_shop/models/genre.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название жанра')

    def __str__(self):
        return self.name

book_shop/models/language.py
from django.db import models


class Language(models.Model):
    name = models.CharField(max_length=30, verbose_name='Язык')

    def __str__(self):
        return self.name

book_shop/forms.py
from django import forms
from book_shop.models import *

class FormBook(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'description', 'image', 'article', 'genres', 'publication_date', 'price', 'is_available', 'language']


class FormAuthor(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name']


class FormGenre(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['name']

book_shop/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView, DetailView, ListView, CreateView

from book_shop.models import *
from book_shop.forms import *

# Create your views here.


class Home(ListView):
    template_name = 'index.html'
    model = Book
    context_object_name = 'books'



class CatalogView(TemplateView):
    template_name = 'catalog.html'


class RegistrationView(TemplateView):
    template_name = 'Registration.html'


class DetailBookView(DetailView):
    template_name = 'detail_book.html'
    model = Book
    context_object_name = 'book'
    pk_url_kwarg = 'id'


class CreateBookView(CreateView):
    template_name = 'create_book.html'
    form_class = FormBook
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authors'] = Author.objects.all()
        context['genres'] = Genre.objects.all()
        context['languages'] = Language.objects.all()
        return context

    def form_invalid(self, form):
        print(form.errors)
        return render(self.request, 'create_book.html', {'form': form})

    def get_success_url(self):
        return reverse('home')


class CreateAuthorView(CreateView):
    template_name = 'create_author.html'
    form_class = FormAuthor
    model = Author

    def get_success_url(self):
        return reverse('home')


class CreateGenreView(CreateView):
    template_name = 'create_author.html'
    form_class = FormGenre
    model = Genre

    def get_success_url(self):
        return reverse('home')

book_shop/templates/Registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Форма регистрации</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="stylesr.css">
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="col-md-6 form-container">
            <form class="p-4" action="index.html">
                <h2 class="text-center mb-3">Регистрация</h2>
                <div class="form-group">
                    <label for="username">Имя пользователя:</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="password">Пароль:</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <div class="form-group d-flex justify-content-between">
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="rememberMe">
                        <label class="form-check-label" for="rememberMe">Запомнить меня</label>
                    </div>
                    <a href="#">Забыли пароль?</a>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Зарегистрироваться</button>
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>      
</body>
</html>

book_shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Книжный магазин{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="headernavfix">
        <header class="text-white text-center py-4">
            <h1>Наш весь ассортимент книг</h1>
        </header>

        <nav class="navbar navbar-expand-lg navbar-dark">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item mr-5 ml-5"><a class="nav-link" href="{% url 'home' %}">Главная</a></li>
                <li class="nav-item mr-5 ml-5"><a class="nav-link" href="catalog.html">Каталог</a></li>
                <li class="nav-item mr-5 ml-5"><a class="nav-link" href="about.html">О нас</a></li>
                <li class="nav-item mr-5 ml-5"><a class="nav-link" href="basket.html">Корзина</a></li>
                <li class="nav-item mr-5 ml-5"><a class="nav-link" href="Registration.html">Регистрация</a></li>
            </ul>
        </nav>
    </div>        <main class="container mt-5">

    {% block content %}

    {% endblock %}
        </main>
<footer class="text-white text-center py-2">
        <p>&copy; 2023 Книжный магазин</p>
    </footer>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
<script src="{% static 'js/open_and_close_window.js' %}"></script>
<script src="{% static 'js/check_datebase.js' %}"></script>

</body>
</html>

book_shop/templates/create_author.html
{% extends 'base.html' %}

{% block title %}Добавить автора{% endblock title %}

{% block content %}
<h2>Добавить автора</h2>
<form id="author-form" method="post" class="row g-3" action="{% url 'create-author' %}">
    {% csrf_token %}
    <div class="mb-3 col-md-6">
        <label for="authorName" class="form-label">Имя автора</label>
        <input type="text" class="form-control" id="authorName" name="name" required>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">Добавить автора</button>
    </div>
</form>

{% endblock content %}

book_shop/templates/create_book.html
{% extends 'base.html' %}

{% block content %}
<h2>Добавление новой книги</h2>
    <form method="post" enctype="multipart/form-data" class="row g-3" action="{% url 'create-book' %}">
        {% csrf_token %}
        <div class="mb-3 col-md-6">
            <label for="id_title" class="form-label">Название</label>
            <input type="text" class="form-control" id="id_title" name="title" value="{{ form.title.value|default:'' }}">
        </div>
        <div class="mb-3 col-md-6">
  <label for="id_author" class="form-label">Автор</label>
  <select class="form-select" id="id_author" name="author">
  <option value="">Выберите автора</option>
  {% for author in authors %}
  <option value="{{ author.id }}" {% if form.instance.author_id == author.id %}selected{% endif %}>
    {{ author.name }}
  </option>
  {% endfor %}
</select>
  <span class="text-secondary">
    Если нет подходящего автора, то <a href="javascript:void(0);" onclick="window.open('{% url 'create-author' %}', 'newwindow', 'width=800,height=600'); return false;">создайте его</a>.

  </span>
</div>
        <div class="mb-3 col-12">
            <label for="id_description" class="form-label">Описание</label>
            <textarea class="form-control" id="id_description" name="description" rows="3">{{ form.description.value|default:'' }}</textarea>
        </div>
        <div class="mb-3 col-12">
    <label for="formFile" class="form-label">Изображение</label>
    <input class="form-control" type="file" id="formFile" name="image">
</div>
        <div class="mb-3 col-md-6">
            <label for="id_article" class="form-label">Артикул</label>
            <input type="text" class="form-control" id="id_article" name="article" value="{{ form.article.value|default:'' }}">
        </div>
        <div class="mb-3 col-md-6">
            <label for="id_price" class="form-label">Цена</label>
            <input type="number" class="form-control" id="id_price" name="price" value="{{ form.price.value|default:'' }}">
        </div>
<div class="mb-3 col-md-6">
  <label for="id_genre" class="form-label">Жанр</label>
  <select class="form-select" id="id_genre" name="genres">
  <option value="">Выберите жанр</option>
  {% for genre in genres %}
  <option value="{{ genre.id }}" {% if form.instance.genre_id == genre.id %}selected{% endif %}>
    {{ genre.name }}
  </option>
  {% endfor %}
</select>
    Если нет подходящего жанра, то <a href="javascript:void(0);" onclick="window.open('{% url 'create-genre' %}', 'newwindow', 'width=800,height=600'); return false;">создайте его</a>.
</div>
    <div class="mb-3 col-md-6">
  <label for="id_language" class="form-label">Язык</label>
  <select class="form-select" id="id_language" name="language">
  <option value="" {% if not form.language.value %}selected{% endif %}>Выберите язык</option>
  {% for language in languages %}
  <option value="{{ language.id }}" {% if form.instance.language_id == language.id %}selected{% endif %}>
    {{ language.name }}
  </option>
  {% endfor %}
</select>
{#        Если нет подходящего языка, то <a href="javascript:void(0);" onclick="window.open('{% url 'create-language' %}', 'newwindow', 'width=800,height=600'); return false;">создайте его</a>.#}

</div>
        <div class="mb-3 col-12">
            <label for="id_publication_date" class="form-label">Дата публикации</label>
            <input type="date" class="form-control" id="id_publication_date" name="publication_date" value="{{ form.publication_date.value|default:'' }}">
        </div>
        <div class="mb-3 col-md-3">
            <label for="id_is_available" class="form-label">В наличии</label>
            <select class="form-select" id="id_is_available" name="is_available">
                <option value="true">Да</option>
                <option value="false">Нет</option>
            </select>
        </div>
<div class="col-12">
            <button type="submit" class="btn btn-primary">Добавить книгу</button>
        </div>
    </form>
{% endblock %}

book_shop/templates/create_genre.html
{% extends 'base.html' %}

{% block content %}
<h2>Добавить жанр</h2>
        <form class="row g-3">
            <div class="mb-3 col-12">
                <label for="genreName" class="form-label">Название жанра</label>
                <input type="text" class="form-control" id="genreName" name="name" required>
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">Добавить жанр</button>
            </div>
        </form>
{% endblock %}

book_shop/templates/detail_book.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
          <h2>Название Книги: {{ book.title }}</h2>

    <div class="col-md-4">
      <img src="{{ book.image.url }}" alt="Название Книги" class="book-image rounded img-fluid">
    </div>
    <div class="col-md-8">
      <div class="info-block text-white">
          <p class="author">Автор Книги: {{ book.author }}</p>
          <p>Описание книги: <br> {{ book.description }}</p>
<p>Жанры: {% for genre in book.genres.all %}{{ genre.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
      <p>Книга переведена на {%  for language in book.language.all %}{{ language.name }} {% if not forloop.last %}, {% endif %}{% endfor %}</p>
      <p>Дата публикации: {{ book.publication_date }}</p>
      <p>Цена: {{ book.price }} тенге</p>
      <p>Артикул: {{ book.article }}</p>
      </div>
    </div>
  </div>
{% endblock %}

book_shop/templates/index.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Книжный магазин</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% block content %}
        {% if books %}
        <div class="carousel">
            <!-- Карусель самых популярных книг -->
            <div id="popularBooksCarousel" class="carousel slide" data-ride="carousel">
                <h2>Новинки</h2>
                <div class="carousel-inner mt-4">
                    <div class="carousel-item active">
                        <div class="row">
                            <div class="col-4">
                                <img src="https://cdn.f.kz/prod/3053/3052926_550.jpg" class="d-block w-100" alt="Book 4">
                            </div>
                            <div class="col-4">
                                <img src="https://cdn.f.kz/prod/3005/3004784_550.jpg" class="d-block w-100" alt="Book 5">
                            </div>
                            <div class="col-4">
                                <img src="https://cdn.f.kz/prod/3002/3001380_550.jpg" class="d-block w-100" alt="Book 6">
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-4">
                                <img src="https://cdn.f.kz/prod/3054/3053230_550.jpg" class="d-block w-100" alt="Book 7">
                            </div>
                            <div class="col-4">
                                <img src="https://cdn.f.kz/prod/3054/3053160_550.jpg" class="d-block w-100" alt="Book 8">
                            </div>
                            <div class="col-4">
                                <img src="https://cdn.f.kz/prod/3054/3053196_550.jpg" class="d-block w-100" alt="Book 9">
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-4">
                                <img src="https://cdn.f.kz/prod/3055/3054189_550.jpg" class="d-block w-100" alt="Book 1">
                            </div>
                            <div class="col-4">
                                <img src="https://cdn.f.kz/prod/3055/3054318_550.jpg" class="d-block w-100" alt="Book 2">
                            </div>
                            <div class="col-4">
                                <img src="https://cdn.f.kz/prod/3037/3036971_550.jpg" class="d-block w-100" alt="Book 3">
                            </div>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#popularBooksCarousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#popularBooksCarousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" ariahidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>

        <div class="bestsellers">
            <!-- Раздел с бестселлерами -->
            <h2>Бестселлеры</h2>
            <div class="row mt-4">
            {% for book in books %}


                 <div class="col-md-2">
                <a href="{% url 'book-detail' book.id %}" class="text-decoration-none">
                    <div class="card h-100">
                        <img src="{{ book.image.url }}" class="card-img-top" alt="Book 1">
                        <div class="card-body">
                            <h5 class="card-title">{{ book.title }}</h5>
                            <p class="card-text">{{ book.author }}</p>
                        </div>
                    </div>
                </a>

                </div>
                        {% endfor %}

            </div>
            {% else %}
            <h1 class="text-center">Товар Отсутствует</h1>

            {% endif %}
        </div>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>